### ISSUE TITLE
Copy to clipboard example is not working

### ISSUE THREAD

**Issue by sifisatz** [bence-toth/react-hook-clipboard#19]
I tried to reproduce the example code and on Click event I took this error:  

```
const ComponentWithClipboard = () => {
  const [clipboard, copyToClipboard] = useClipboard()
  const toClipboard = 'I want to go to the clipboard'

  return (
    <div className="App">
      <p>Clipboard content: {clipboard}</p>
      <button onClick={() => copyToClipboard(toClipboard)}>
        Copy to clipboard
      </button>
    </div>
  )
}
```
```
Unhandled Rejection (TypeError): 'clipboard-write' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
```

**Comment by bence-toth** [comment]
Hi @sifisatz, thank you for reaching out.

I'd like to get a bit more info on this. What browser are you using? Are you trying to use the feature in a secure (HTTPS) context?

Have you checked the [Caveats section](https://github.com/bence-toth/react-hook-clipboard#caveats) of the readme?

**Comment by sifisatz** [comment]
Hello ,
I tested on https ang got this error 

Thanks for your time

**Comment by bence-toth** [comment]
I tried to reproduce this but I couldn't. What browser and which version are you using?
